config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/dashboard', to: 'pages#dashboard'
  # verb '/path', to 'controller#action'

      resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
        resources :bookings, only: [:new, :create, :show]
      end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_one_attached :photo
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user_id, presence: true
  validates :item_id, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_many :bookings, dependent: :destroy

  belongs_to :user
  has_many :photos

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :location, presence: true
  validates :photo, presence: true

  def self.search(query)
    where("name ILIKE ?", "%#{query}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :received_bookings, through: :items, source: :bookings

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.item = Item.find(params[:item_id])
    @booking.user = current_user

    if @booking.save
      redirect_to @booking.item , notice: 'Booking was successfully created.'
      # redirect_to booking_path(@booking)
    else
      render 'items/show'
    end
  end

  def index
    @bookings = Booking.all
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :configure_permitted_parameters, if: :devise_controller?

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save

      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
     # Will raise ActiveModel::ForbiddenAttributesError
  end

  def show
    @item = Item.find(params[:id])
    @booking = @item.bookings.build



    @markers = [
      {
        lat: @item.latitude,
        lng: @item.longitude
      }
    ]

  end

  def index
    @items = Item.all
    if params[:query].present?
      @items = Item.search(params[:query])
    else
      @items = Item.all
    end
  end

  def item_params
    params.require(:item).permit(:name, :price, :description, :location, :photo)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to dashboard_path(@item)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to dashboard_path, status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @items = Item.all.limit(4)
  end

  def search
    @items = []

    if params[:query].present?
      @results = PgSearch.multisearch(params[:query])
      @results.each do |result|
        if result.searchable_type == "Item"
          @item = Item.find(result.searchable_id)
          @items.push(@item)
        end
      end
    end
  end

  def dashboard
    @user = current_user
    @items = Item.all.where(user_id: current_user.id).limit(4) if current_user
    @bookings = Booking.all.where(user_id: current_user.id) if current_user
    @received_bookings = current_user.received_bookings
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="tohomepage d-flex justify-content-around">
    <%= link_to "Back to homepage", root_path %>
    <%= link_to "Add a new item", new_item_path %>
  </div>

  <% @bookings.each do |booking| %>
      <div class="col-3">
        <div class="card d-flex justify-content-between" style="height:500px">
        <% if item.photo.attached?%>
          <%= cl_image_tag item.photo.key, class:"card-img-top", height: 300 %>
        <% end %>

            <div class="card-body">
              <h2>
                <%= link_to item.name, item_path(item), class: "text-decoration-none" %>
              </h2>
              <p>
                <%= item.description %>
              </p>
              <p>
                <%= item.price %>
              </p>
            </div>
          </div>
        </div>
      <% end %>

  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">

  <h2>book this item</h2>

  <%= simple_form_for(@booking) do |f| %>
    <!-- [...] -->
    <%= f.input :start_date, as: :date %>
    <%= f.input :end_date, as: :date %>
    <%= f.submit %>
    <!-- [...] -->
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container-fluid text-center mt-3">
  <div class="item-photo">
        <%= image_tag(@item.photo.url, width: 400, height: 300, crop: :fill) %>

    </div><br>
  <div>
    <h3><strong><%= @item.name %></strong></h3>
    <p><%= @item.description %></p>
    <p><%= @item.location %></p>
    <p><%= @item.price %></p>
  </div>
  </div>

  <div>

</div>

app/views/items/edit.html.erb
<div class="container px-4 mt-4">
  <h2>Edit your item</h2>
  <hr class="mt-0 mb-4">


  <%= simple_form_for(@item, html: { multipart: true }) do |f| %>
    <!-- [...] -->
    <%= f.input :name, as: :string %>
    <%= f.input :price, as: :integer %>
    <%= f.input :description, as: :string %>
    <%= f.input :location, as: :string %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Edit", class: "btn btn-primary" %>
    <!-- [...] -->
  <% end %>
</div>

app/views/items/index.html.erb
<div class="tohomepage d-flex justify-content-around">
  </div>


<div class="container px-4 mt-4">
  <h2>All listings</h2>
  <hr class="mt-0 mb-4">
  <div class="row">

    <% @items.each do |item| %>
      <div class="col-3">
        <div class="card d-flex justify-content-between card-item">
        <% if item.photo.attached?%>
          <%= cl_image_tag item.photo.key, class:"card-img", height: 300 %>
        <% end %>

            <div class="card-body">
              <h4>
                <%= link_to item.name.capitalize, item_path(item), class: "text-decoration-none" %>
              </h4>
              <hr class="mt-0 mb-4">
              <p>
                <%= item.description %>
              </p>
              <p>€<%= item.price %>.-</p>
              <p><%= item.location %></p>
            </div>

        </div>
        </div>
      <% end %>
</div>
</div>

app/views/items/new.html.erb
<div class="container px-4 mt-4">
  <h2>Add new item</h2>
  <hr class="mt-0 mb-4">


  <%= simple_form_for(@item, html: { multipart: true }) do |f| %>
    <!-- [...] -->
    <%= f.input :name, as: :string %>
    <%= f.input :price, as: :integer %>
    <%= f.input :description, as: :string %>
    <%= f.input :location, as: :string %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Add item", class: "btn btn-primary" %>
    <!-- [...] -->
  <% end %>
</div>

app/views/items/show.html.erb
  <style>


  </style>


<div class="container px-4 mt-4">
    <h2>Item</h2>
    <hr class="mt-0 mb-4">
    <div class="card mb-4 mx-auto w-100 card-item">

    <div class=book-an-item>
      <div class=card-and-details>
        <div class="card-img">
          <%= image_tag(@item.photo.url, width: 400, height: 300, crop: :fill) %>
          </div><br>
          <div>
            <h4><strong><%= @item.name.capitalize %></strong></h4>
            <hr class="mt-0 mb-4">
            <p><%= @item.description %></p>
            <p><%= @item.location %></p>
            <p>€<%= @item.price %>,-</p>
        </div>
        </div>

        <div class="booking-form">
          <%= simple_form_for([@item, @booking], html: { multipart: true }) do |f| %>
            <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
            <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
            <%= f.submit "Create booking", class: "btn btn-primary"%>
          <% end %>
        </div>
    </div>



</div>

      <div style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAParty</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  </head>

  <body>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>


    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container-xl px-4 mt-4">
  <h2>Dashboard</h2>
  <hr class="mt-0 mb-4">

    <div class="row">
      <div class="col-xl-4">
            <!-- Profile picture card-->
          <div class="card mb-4 mb-xl-0">
              <div class="card-header">Profile Picture</div>
                <div class="card-body text-center">
                    <!-- Profile picture image-->
                  <div class="profile-picture mb-2">
                  <%= cl_image_tag current_user.avatar.key, class:"card-img-top card-user-avatar rounded-circle" if current_user.avatar.attached? %>
                  </div>


                </div>
          </div>
      </div>
        <div class="col-xl-8">
            <!-- Account details card-->
          <div class="card mb-4">
            <div class="card-header">Account Details</div>
              <div class="card-body">
                <form>
                        <!-- Form Group (email)-->
                  <div class="mb-3">
                    <p>Email:
                    <br>
                    <%= current_user.email %></p>
                  </div>
              </div>
                </form>
          </div>
          </div>
      </div>


  <div class="col-xl-12 d-flex align-items-center justify-content-center">
    <div class="card mb-4 mx-auto w-100 card-item card-listings">
      <div class="card-header">Your listings</div>
        <div class="card-body row">
           <% @items.each do |item| %>
            <div class="col-3">
           <%= cl_image_tag item.photo.key, class:"card-img", height: 300 if item.photo.attached? %>
           <div class="card-body">
           <h4><%= link_to item.name.capitalize, item_path(item) %></h4>
           <hr class="mt-0 mb-4">
           <p>€<%= item.price %>.-</p>
           <p><%= item.location %></p>
            </div>
           <%= link_to "Edit", edit_item_path(item), class: "btn btn-primary", class: "btn-dashboard"%>
           <%= link_to "Delete", item_path(item),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary", class: "btn-dashboard"%>
              </div>
           <% end %>
           </div>
      </div>
    </div>


  <div class="col-xl-12 d-flex align-items-center justify-content-center">
    <div class="card mb-4 mx-auto w-100 card-item card-listings">
      <div class="card-header">My bookings</div>
        <div class="card-body row">
           <% @bookings.each do |booking| %>
            <div class="col-3">
           <%= cl_image_tag booking.item.photo.key, class:"card-img", height: 300 if booking.item.photo.attached? %>
              <div class="card-body">
                <h4><%= link_to booking.item.name.capitalize, item_path(booking.item) %></h4>
                <hr class="mt-0 mb-4">
                <p>€<%= booking.item.price %>.-</p>
                <p><%= booking.item.location %></p>
                <hr class="mt-0 mb-4">
                <p>From: <%= booking.start_date %></p>
                <p>Until: <%= booking.end_date %></p>
                </div>
              </div>
           <% end %>
           </div>
      </div>
    </div>



  <div class="col-xl-12 d-flex align-items-center justify-content-center">
    <div class="card mb-4 mx-auto w-100 card-booking">

      <div class="card-header">My received bookings</div>
        <div class="card-body row">
        <p>No received bookings yet.</p>
        <% @received_bookings.each do |booking| %>
          <div class="col-3">
           <%= cl_image_tag booking.item.photo.key, class:"card-img", height: 300 if booking.item.photo.attached? %>
            <div class="card-body">
              <h4><%= link_to booking.item.name.capitalize, item_path(booking.item) %></h4>
              <hr class="mt-0 mb-4">
              <p>€<%= booking.item.price %>.-</p>
              <p><%= booking.item.location %></p>
              <hr class="mt-0 mb-4">
              <p>From: <%= booking.start_date %></p>
              <p>Until: <%= booking.end_date %></p>
              </div>

              </div>
           <% end %>
           </div>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="homepage">
  <div class="banner" style ="background-image: url('https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D');">
    <div class="container">
      <div class="head">
        <h1>Airpnp</h1>
        <h5>Everything you need for a party!</h5>
      </div>
    </div>
  </div>

  <div class="items">
    <h2 id="popular">
      Most popular this week
    </h2>

    <div class="container">
      <div class="row center">
        <% @items.each do |item| %>
          <div class="col-3">
            <div class="card d-flex justify-content-between card-item">
                <%= cl_image_tag(item.photo.key, class:"card-img")%>

                <div class="card-body">
                  <h4>
                    <%= link_to item.name.capitalize, item_path(item), class: "text-decoration-none" %>
                  </h4>
                  <hr class="mt-0 mb-4">
                  <p>
                    <%= item.description %>
                  </p>
                  <p>€<%= item.price %>.-
                  </p>
                  <p><%= item.location %></p>
                </div>

            </div>
            </div>
          <% end %>
      </div>
    </div>
    <div class="all text-center">
    <%= link_to "All listings", items_path, class: "btn btn-primary"%>
    </div>
  </div>



</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex flex-column align-items-center justify-content-center"
     style="position: relative; left: 0; bottom: 0; width: 100vw;">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Romee and the Anna's
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%# logo le wagon %>
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://media.istockphoto.com/id/1493351005/nl/vector/mirror-disco-ball-with-glitters-icon-shining-nightclub-sphere-dance-music-party-discoball.jpg?s=612x612&w=0&k=20&c=KXj4wsIRpi--sYcDH_ypTLU5rySe5_nH9JfqLvziLHc=" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="search-bar" class="row justify-content-center">
    <div class="col-sm-12">
      <div id="items">
        <%= form_with url: items_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control form-control-search",
            placeholder: "Search for an item"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary ml-3"%>
    <% end %>
      </div>
    </div>
  </div>

    <%# login logic %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%# deleted link to home page %>
          </li>
          <li class="nav-item mr-3" style="padding-top: 9px;">
            <%= link_to "Add new item", "/items/new", class: "btn btn-primary"%>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: "avatar", alt: "User avatar" %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "Default avatar" %>
            <% end %>          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "All listings", "/items", class: "dropdown-item" %>
              <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

</div>